### ISSUE TITLE
Plugins flags

### ISSUE THREAD

**Issue by RiCoTeRoX** [vickylance/phaser3-parcel-ts-starter#1]
Hi !!!
nice work.

One question, how can you set global preferences with parcel ?
in webpack it use with definePlugin option

`"typeof CANVAS_RENDERER": JSON.stringify(true),
      "typeof WEBGL_RENDERER": JSON.stringify(true),
      "typeof EXPERIMENTAL": JSON.stringify(false),
      "typeof PLUGIN_CAMERA3D": JSON.stringify(false),
      "typeof PLUGIN_FBINSTANT": JSON.stringify(false)`

but in parcel ?

thx in advanced

**Comment by vickylance** [comment]
Sorry for the late reply. This is for any future reference. 

You can either use `.env` file to mention any flags. Or [npm configs](https://docs.npmjs.com/misc/config)

Or you can just set it onto the window object in the index.html before the script tag.
